// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyLocation.Data;

#nullable disable

namespace PharmacyLocation.Data.Migrations
{
    [DbContext(typeof(PharmacyLocationContext))]
    [Migration("20240211043738_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmacyLocation.Core.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PharmacyLocation.Core.FavoriteUserProduct", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ProductId", "UserId");

                    b.ToTable("FavoriteUserProducts");
                });

            modelBuilder.Entity("PharmacyLocation.Core.Pharmacy", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsOpenAllHours")
                        .HasColumnType("bit");

                    b.Property<string>("UrlImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("PharmacyLocation.Core.PharmacyProduct", b =>
                {
                    b.Property<string>("IdProduct")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdPharmacy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IdProduct", "IdPharmacy");

                    b.HasIndex("IdPharmacy");

                    b.ToTable("PharmacyProducts");
                });

            modelBuilder.Entity("PharmacyLocation.Core.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PharmacyLocation.Core.Category", b =>
                {
                    b.OwnsOne("PharmacyLocation.DescriptionVo", "Description", b1 =>
                        {
                            b1.Property<string>("CategoryId")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("PharmacyLocation.Core.FavoriteUserProduct", b =>
                {
                    b.HasOne("PharmacyLocation.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmacyLocation.Core.Pharmacy", b =>
                {
                    b.OwnsOne("PharmacyLocation.DescriptionVo", "Description", b1 =>
                        {
                            b1.Property<string>("PharmacyId")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.HasKey("PharmacyId");

                            b1.ToTable("Pharmacies");

                            b1.WithOwner()
                                .HasForeignKey("PharmacyId");
                        });

                    b.OwnsOne("PharmacyLocation.LocationVo", "Location", b1 =>
                        {
                            b1.Property<string>("PharmacyId")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.Property<double>("Presicion")
                                .HasColumnType("float");

                            b1.HasKey("PharmacyId");

                            b1.ToTable("Pharmacies");

                            b1.WithOwner()
                                .HasForeignKey("PharmacyId");
                        });

                    b.OwnsMany("PharmacyLocation.PharmacySchedule", "PharmacySchedules", b1 =>
                        {
                            b1.Property<int>("Day")
                                .HasColumnType("int");

                            b1.Property<string>("PharmacyId")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<TimeSpan>("ClosingTime")
                                .HasColumnType("time");

                            b1.Property<TimeSpan>("OpeningTime")
                                .HasColumnType("time");

                            b1.HasKey("Day", "PharmacyId");

                            b1.HasIndex("PharmacyId");

                            b1.ToTable("PharmacySchedule");

                            b1.WithOwner("Pharmacy")
                                .HasForeignKey("PharmacyId");

                            b1.Navigation("Pharmacy");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("PharmacySchedules");
                });

            modelBuilder.Entity("PharmacyLocation.Core.PharmacyProduct", b =>
                {
                    b.HasOne("PharmacyLocation.Core.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("IdPharmacy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyLocation.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pharmacy");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmacyLocation.Core.Product", b =>
                {
                    b.OwnsMany("PharmacyLocation.Core.CategoryProduct", "CategoryProducts", b1 =>
                        {
                            b1.Property<string>("CategoryId")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("ProductId")
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("CategoryId", "ProductId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("CategoryProduct");

                            b1.WithOwner("Product")
                                .HasForeignKey("ProductId");

                            b1.Navigation("Product");
                        });

                    b.OwnsOne("PharmacyLocation.DescriptionVo", "Description", b1 =>
                        {
                            b1.Property<string>("ProductId")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("CategoryProducts");

                    b.Navigation("Description")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
